### ISSUE TITLE
EPG not accurate

### ISSUE THREAD

**Issue by markster1700** [InsolenceWillow/insolencetvgo#13]
### Describe your issue

Sometimes the provided EPG is down or not accurate. 
I would recommend we use https://epgshare01.online/epgshare01/ site. It has many EPG's and refreshes twice a day.
I have tested it and its very good. Something to consider.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by InsolenceWillow** [comment]
It'll be added
