### ISSUE TITLE
Secured channels

### ISSUE THREAD

**Issue by markster1700** [InsolenceWillow/insolencetvgo#14]
### Describe your issue

All entries with http://38.22.17.37:6969 do require authentication. I don't know if this is intended or a mistake.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by InsolenceWillow** [comment]
I switched all of them with http://74.48.44.156:1234

**Comment by rushereeeeee** [comment]
ESPN’s moveonjoy link seems to be broken :/

**Comment by InsolenceWillow** [comment]
I'll switch the feed

**Comment by rushereeeeee** [comment]
k
