### ISSUE TITLE
Add: WCBS (New York) CBS East

### ISSUE THREAD

**Issue by macavelly** [InsolenceWillow/insolencetvgo#4]
### Channel ID (required)

wcbs

### Channel Name

CBS East

### Stream URL (required)

https://thetvapp.to/tv/wcbs-new-york-cbs-east-live-stream/

### Quality

None

### Label

None

### Notes

The one in the current playlist is not correct. 

`#EXTINF:-1 tvg-id="CBSWBZ.us" tvg-name="CBS East" tvg-logo="https://cordcutting.com/wp-content/uploads/2022/03/CBS-Logo.png" group-title="Live Channels",CBS East (Boston)
http://fl1.moveonjoy.com/CBSEAST/index.m3u8`

It's actually a stream to channel 38 (WSBK-TV). I've been trying to get a stream to all the local channels in NY. CBS seems to be the only one I can't find. The link I provided does have the right stream but I believe its tokened.

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by macavelly** [comment]
Found the right one http://myteve.online:8080/GenIptv2023/XkgMCdR7PJzShK5m/170018
It was in insolencetvgo/myteve.online.m3u

**Comment by InsolenceWillow** [comment]
I Found A Better Stream: http://38.22.17.37:6969/stream/asd/595/master.m3u8

**Comment by InsolenceWillow** [comment]
And I Will Update The InsolenceTVGo Playlist

**Comment by macavelly** [comment]
Amazing! Thanks a lot. I was having some "Stream ends prematurely" errors with the myteve link.

**Comment by InsolenceWillow** [comment]
Should Be On The Playlist Now

**Comment by rushereeeeee** [comment]
Apparently you have to sign in to view it
![IMG_0764](https://github.com/user-attachments/assets/69a222d2-61b0-4e8e-80bd-ec7c57db9938)

**Comment by macavelly** [comment]
yep getting that error now, was working before.

**Comment by InsolenceWillow** [comment]
I'll Find Another
