### ISSUE TITLE
Add: NHK World Japan

### ISSUE THREAD

**Issue by haworthia-hime** [InsolenceWillow/insolencetvgo#5]
### Channel ID (required)

NHKWorldJapan.jp

### Channel Name

NHK World-Japan

### Stream URL (required)

https://nhkwlive-ojp.akamaized.net/hls/live/2003459/nhkwlive-ojp-en/index_1M.m3u8

### Quality

1080p

### Label

None

### HTTP Referrer

https://www3.nhk.or.jp/nhkworld/en/live/

### Notes

Hope I'm doing this correctly! I believe this should go in the main insolencetvgo m3u. Thanks!

### Contributing Guide

- [ ] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by InsolenceWillow** [comment]
Japan Channels Isn't Something We Add On The InsolenceTVGo Playlist!

**Comment by haworthia-hime** [comment]
> Japan Channels Isn't Something We Add On The InsolenceTVGo Playlist!

This is an English-language channel that you can find on American TV providers! You can take a look at their website [right here](https://www3.nhk.or.jp/nhkworld/).

**Comment by InsolenceWillow** [comment]
It Says Specifically That It Is An International Network, As In It's Not US! And I Don't See It On My Comcast Provider!

**Comment by haworthia-hime** [comment]
> It Says Specifically That It Is An International Network, As In It's Not US! And I Don't See It On My Comcast Provider!
Going along those lines, wouldn't [Caracol](https://en.wikipedia.org/wiki/Caracol_Televisi%C3%B3n), a Columbian television network that is on this list, not be allowed, then? I'm a bit confused now.

https://www3.nhk.or.jp/nhkworld/en/tv/howto/

This link shows that it's on multiple cable services, I'm able to access it fine. I understand it if you'd rather not add it, but considering how it's an English-language channel that is viewable in America as part of a base cable subscription, I think it might be useful for this service. Just something to think about.
![image](https://github.com/user-attachments/assets/0b4a5d66-d8e2-4991-b813-227792489762)

**Comment by InsolenceWillow** [comment]
Caracol Is ACTUALLY On My Comcast TV Listings

**Comment by InsolenceWillow** [comment]
Oh, I Think It's Because I'm In The East Coast And Those Comcast Listings Are In The West Coast, Apologies, I'll See What I Can Do To Add It!

**Comment by haworthia-hime** [comment]
> Oh, I Think It's Because I'm In The East Coast And Those Comcast Listings Are In The West Coast, Apologies, I'll See What I Can Do To Add It!

No worries! That must be it, then, thank you for your understanding! Thank you for your hard work.

**Comment by InsolenceWillow** [comment]
Should Be On The Playlist Now!
